language: python
python:
    - "3.6"

sudo: true  # Needed for coreir-dev branch building coreir from source (installing g++-4.9 through apt)

before_install:
    - git clone https://github.com/phanrahan/magma.git
    - pip install -e magma
    - source magma/.travis/install_coreir.sh

install:
    - pip install pytest-cov
    - pip install fabricate delegator.py
    - pip install -e .

script:
    - ./scripts/run_tests.sh
