language: python
python:
    - "3.6"

sudo: true  # Needed for coreir-dev branch building coreir from source (installing g++-4.9 through apt)

before_install:
    - git clone https://github.com/phanrahan/magma.git
    - pip install -e magma
    - source magma/.travis/install_coreir.sh

install:
    - pip install pytest-cov
    - pip install fabricate delegator.py
    - pip install -e .

script:
    - py.test tests/test_verilog
    - py.test --target coreir tests/test_coreir
    - py.test --target ice40 tests/test_ice40 tests/test_mantle40
    - py.test --target spartan3 tests/test_spartan3 
    - py.test --target spartan6 tests/test_spartan6 
    - py.test --target coreir tests/test_mantle
    - py.test --target ice40 tests/test_mantle
    - py.test --target spartan3 tests/test_mantle
    - py.test --target spartan6 tests/test_mantle
